server:
  port: 8081
spring:
  application:
    name:
      microservice-config-service
    cloud:
      config:
        server:
          git:
            default-label:
              main
            uri:
              https://github.com/Oswaldo-Alberto-Cabrejos-Ronceros/microservicios-investigacion-herramientas-servidor-config.git
            search-paths:
              config-data