server:
  port: 8081

spring:
  application:
    name: microservice-config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Oswaldo-Alberto-Cabrejos-Ronceros/microservicios-investigacion-herramientas-servidor-config.git
          default-label: docker
          search-paths: config-data